### PR TITLE
Book Recommendations engine

### PR DESCRIPTION
**Pull request by cshinaver**

### CODE REVIEW

**Comment by cshinaver** [comment]
@mperez14 @jhuseman Could I get a review on this?

**Comment by cshinaver** [comment]
I tested it out locally and on the live server. It uses the same database that the main server uses. In order to get recommendations for a user, we send a POST request to `http://bookfinderrecommender.herokuapp.com` with the POST arguments `user_id` and `number_of_recommendations` set to integer values.

**Comment by cshinaver** [comment]
```
In [1]: import requests

In [2]: requests.post("http://bookfinderrecommender.herokuapp.com/get-recommendation", data = {"user_id":3, "number_of_preferences":3}).content
Out[2]: '[{"item_id":9,"value":0.8888889},{"item_id":5,"value":0.50793654},{"item_id":1,"value":0.50793654}]'
```

**Comment by mperez14** [comment]
Approved

**Pull request merged**
